---
#metricsEndpoints:
#  - indexer:
#      esServers: [http://elastic-elk.apps.rsevilla.kube-burner.com]
#      esServers: [%url%]
#      insecureSkipVerify: true
#      defaultIndex: kube-burner
#      type: elastic
global:
  gc: {{.GC}}
  measurements:
    - name: podLatency

jobs:
  - name: api-intensive-v1
    jobIterations: 400
    qps: 15
    burst: 15
    namespacedIterations: true
    namespace: api-intensive-v1
    podWait: false
    cleanup: false
    waitWhenFinished: true
    objects:
      - objectTemplate: templates/deployment.yaml
        replicas: 1
      - objectTemplate: templates/configmap.yaml
        replicas: 1
      - objectTemplate: templates/secret.yaml
        replicas: 1
      - objectTemplate: templates/service.yaml
        replicas: 1

#  - name: api-intensive-patch
#    jobType: patch
#    jobIterations: 450
#    qps: 15
#    burst: 15
#    objects:
#      - kind: Deployment
#        objectTemplate: templates/deployment_patch_add_label.json
#        labelSelector: {kube-burner-job: api-intensive}
#        patchType: "application/json-patch+json"
#        apiVersion: apps/v1
#      - kind: Deployment
#        objectTemplate: templates/deployment_patch_add_pod_2.yaml
#        labelSelector: {kube-burner-job: api-intensive}
#        patchType: "application/apply-patch+yaml"
#        apiVersion: apps/v1
#      - kind: Deployment
#        objectTemplate: templates/deployment_patch_add_label.yaml
#        labelSelector: {kube-burner-job: api-intensive}
#        patchType: "application/strategic-merge-patch+json"
#        apiVersion: apps/v1

#  - name: api-intensive-remove
#    qps: 15
#    burst: 15
#    jobType: delete
#    waitForDeletion: true
#    objects:
#      - kind: Deployment
#        labelSelector: {kube-burner-job: api-intensive}
#        apiVersion: apps/v1

#  - name: ensure-pods-removal
#    qps: 15
#    burst: 15
#    jobType: delete
#    waitForDeletion: true
#    objects:
#      - kind: Pod
#        labelSelector: {kube-burner-job: api-intensive}

#  - name: remove-services
#    qps: 15
#    burst: 15
#    jobType: delete
#    waitForDeletion: true
#    objects:
#      - kind: Service
#        labelSelector: {kube-burner-job: api-intensive}

#  - name: remove-configmaps-secrets
#    qps: 2
#    burst: 2
#    jobType: delete
#    objects:
#      - kind: ConfigMap
#        labelSelector: {kube-burner-job: api-intensive}
#      - kind: Secret
#        labelSelector: {kube-burner-job: api-intensive}
